// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Game result for public API (excludes GridSolution)
type GameResult struct {
	ID            string     `json:"id"`
	GuestID       string     `json:"guestId"`
	PuzzleID      string     `json:"puzzleId"`
	GridCurrent   [][]*Cell  `json:"gridCurrent"`
	TotalMistakes int        `json:"totalMistakes"`
	Status        GameStatus `json:"status"`
	CreatedAt     string     `json:"createdAt"`
	UpdatedAt     string     `json:"updatedAt"`
}

// Guest set progress
type GuestSetProgress struct {
	GuestID          string  `json:"guestId"`
	SetID            string  `json:"setId"`
	PuzzlesCompleted int     `json:"puzzlesCompleted"`
	IsUnlocked       bool    `json:"isUnlocked"`
	IsCompleted      bool    `json:"isCompleted"`
	UnlockedAt       *string `json:"unlockedAt,omitempty"`
	CompletedAt      *string `json:"completedAt,omitempty"`
	CurrentStamina   int     `json:"currentStamina"`
	CurrentScore     int     `json:"currentScore"`
}

// Result of making a single move
type MoveResult struct {
	Game          *Game        `json:"game"`
	IsCorrect     bool         `json:"isCorrect"`
	Feedback      CellFeedback `json:"feedback"`
	TotalMistakes int          `json:"totalMistakes"`
	IsGameOver    bool         `json:"isGameOver"`
}

type Mutation struct {
}

// Statistics for a specific player
type PlayerStats struct {
	GuestID          string `json:"guestId"`
	PuzzlesCompleted int    `json:"puzzlesCompleted"`
	TotalPuzzles     int    `json:"totalPuzzles"`
}

// Position in grid
type Position struct {
	Row int `json:"row"`
	Col int `json:"col"`
}

// Puzzle from puzzle pool
type Puzzle struct {
	ID                 string      `json:"id"`
	Grid               [][]int     `json:"grid"`
	PrefilledPositions []*Position `json:"prefilledPositions"`
	Difficulty         *string     `json:"difficulty,omitempty"`
	CreatedAt          string      `json:"createdAt"`
}

// Puzzle set/group
type PuzzleSet struct {
	ID         string `json:"id"`
	SetOrder   int    `json:"setOrder"`
	Difficulty string `json:"difficulty"`
	CreatedAt  string `json:"createdAt"`
}

// Statistics for a specific puzzle
type PuzzleStats struct {
	PuzzleID        string  `json:"puzzleId"`
	TotalPlayers    int     `json:"totalPlayers"`
	TotalCompleted  int     `json:"totalCompleted"`
	AverageMistakes float64 `json:"averageMistakes"`
}

// Puzzle with status for a guest
type PuzzleWithStatus struct {
	Puzzle          *Puzzle      `json:"puzzle"`
	Status          PuzzleStatus `json:"status"`
	SolvedPositions []*Position  `json:"solvedPositions"`
	SetOrder        int          `json:"setOrder"`
}

type Query struct {
}

// Result of submitting multiple answers
type SubmitAnswerResult struct {
	Game    *GameResult         `json:"game"`
	Results []*CellVerifyResult `json:"results"`
}

// Puzzle status enum
type PuzzleStatus string

const (
	PuzzleStatusAvailable PuzzleStatus = "AVAILABLE"
	PuzzleStatusPlaying   PuzzleStatus = "PLAYING"
	PuzzleStatusCompleted PuzzleStatus = "COMPLETED"
	PuzzleStatusArchived  PuzzleStatus = "ARCHIVED"
	PuzzleStatusAdBlock   PuzzleStatus = "AD_BLOCK"
)

var AllPuzzleStatus = []PuzzleStatus{
	PuzzleStatusAvailable,
	PuzzleStatusPlaying,
	PuzzleStatusCompleted,
	PuzzleStatusArchived,
	PuzzleStatusAdBlock,
}

func (e PuzzleStatus) IsValid() bool {
	switch e {
	case PuzzleStatusAvailable, PuzzleStatusPlaying, PuzzleStatusCompleted, PuzzleStatusArchived, PuzzleStatusAdBlock:
		return true
	}
	return false
}

func (e PuzzleStatus) String() string {
	return string(e)
}

func (e *PuzzleStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PuzzleStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PuzzleStatus", str)
	}
	return nil
}

func (e PuzzleStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PuzzleStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PuzzleStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
