package model

// Game represents a game session
type Game struct {
	ID              string     `json:"id"`
	GuestID         string     `json:"guestId"`
	PuzzleID        string     `json:"puzzleId"`
	Grid            [][]*Cell  `json:"grid"`
	TotalMistakes   int        `json:"totalMistakes"`
	Status          GameStatus `json:"status"`
	TokensUsed      int        `json:"tokensUsed"`
	TokensRemaining int        `json:"tokensRemaining"`
	CreatedAt       string     `json:"createdAt"`
}

// Cell represents a single cell in the grid
type Cell struct {
	Row         int           `json:"row"`
	Col         int           `json:"col"`
	Value       *int          `json:"value"`
	IsPreFilled bool          `json:"isPreFilled"`
	Feedback    *CellFeedback `json:"feedback"`
}

// GameStatus enum
type GameStatus string

const (
	GameStatusPlaying   GameStatus = "PLAYING"
	GameStatusCompleted GameStatus = "COMPLETED"
)

// CellFeedback enum
type CellFeedback string

const (
	CellFeedbackCorrect CellFeedback = "CORRECT"
	CellFeedbackTooLow  CellFeedback = "TOO_LOW"
	CellFeedbackTooHigh CellFeedback = "TOO_HIGH"
)

// CellInput for filling cells
type CellInput struct {
	Row   int `json:"row"`
	Col   int `json:"col"`
	Value int `json:"value"`
}

// VerifyResult represents verification results
type VerifyResult struct {
	Game              *Game               `json:"game"`
	Results           []*CellVerifyResult `json:"results"`
	AllCorrect        bool                `json:"allCorrect"`
	MistakesThisRound int                 `json:"mistakesThisRound"`
}

// CellVerifyResult represents a single cell verification result
type CellVerifyResult struct {
	Row      int          `json:"row"`
	Col      int          `json:"col"`
	Feedback CellFeedback `json:"feedback"`
}

// LeaderboardEntry represents a leaderboard entry
type LeaderboardEntry struct {
	ID        string `json:"id"`
	GuestID   string `json:"guestId"`
	Username  string `json:"username"`
	Mistakes  int    `json:"mistakes"`
	CreatedAt string `json:"createdAt"`
}

// CompleteGameResult represents the result of completing a game
type CompleteGameResult struct {
	Entry *LeaderboardEntry `json:"entry"`
	Rank  int               `json:"rank"`
}

// Puzzle is defined in models_gen.go (auto-generated by gqlgen)

// TODO: ChatResponse - Add back when implementing AI chat
// type ChatResponse struct {
// 	Message         string `json:"message"`
// 	TokensUsed      int    `json:"tokensUsed"`
// 	TokensRemaining int    `json:"tokensRemaining"`
// }
