// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

// Puzzle from puzzle pool
type Puzzle struct {
	ID        string  `json:"id"`
	Grid      [][]int `json:"grid"`
	Solution  [][]int `json:"solution"`
	CreatedAt string  `json:"createdAt"`
}

type Query struct {
}
