-- Migration: Add guest_id to game_sessions and leaderboard
-- Run: docker exec -i sum100-db psql -U postgres -d sum100game < backend/internal/database/migrations/004_add_guest_id.sql

-- Add guest_id to game_sessions to track which guest created the game
ALTER TABLE game_sessions 
ADD COLUMN IF NOT EXISTS guest_id UUID;

-- Add guest_id to leaderboard for linking with guest users
ALTER TABLE leaderboard 
ADD COLUMN IF NOT EXISTS guest_id UUID;

-- Index for finding games by guest
CREATE INDEX IF NOT EXISTS idx_game_sessions_guest_id ON game_sessions(guest_id);

-- Index for finding leaderboard entries by guest
CREATE INDEX IF NOT EXISTS idx_leaderboard_guest_id ON leaderboard(guest_id);

COMMENT ON COLUMN game_sessions.guest_id IS 'UUID generated by client to identify guest user';
COMMENT ON COLUMN leaderboard.guest_id IS 'UUID generated by client to identify guest user';
