package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/kenshero/100sumgame/internal/domain"
	"github.com/kenshero/100sumgame/internal/graphql/generated"
	"github.com/kenshero/100sumgame/internal/graphql/model"
)

// CreateGame mutation resolver
func (r *mutationResolver) CreateGame(ctx context.Context, guestID string) (*model.Game, error) {
	guestUUID, err := resolveGuestUUID(ctx, guestID)
	if err != nil {
		return nil, err
	}

	game, err := r.GameService.CreateGame(ctx, guestUUID)
	if err != nil {
		return nil, err
	}

	return domainGameToModel(game), nil
}

// FillCells mutation resolver
func (r *mutationResolver) FillCells(ctx context.Context, gameID string, cells []*model.CellInput) (*model.Game, error) {
	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	domainCells := make([]domain.CellInput, len(cells))
	for i, cell := range cells {
		domainCells[i] = domain.CellInput{
			Row:   cell.Row,
			Col:   cell.Col,
			Value: cell.Value,
		}
	}

	game, err := r.GameService.FillCells(ctx, id, domainCells)
	if err != nil {
		return nil, err
	}

	return domainGameToModel(game), nil
}

// MakeMove mutation resolver
func (r *mutationResolver) MakeMove(ctx context.Context, gameID string, row int, col int, value int) (*model.MoveResult, error) {
	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	result, err := r.GameService.MakeMove(ctx, id, row, col, value)
	if err != nil {
		return nil, err
	}

	feedback := model.CellFeedback(result.Feedback)

	return &model.MoveResult{
		Game:          domainGameToModel(result.Game),
		IsCorrect:     result.IsCorrect,
		Feedback:      feedback,
		TotalMistakes: result.TotalMistakes,
		IsGameOver:    result.IsGameOver,
	}, nil
}

// VerifyGame mutation resolver
func (r *mutationResolver) VerifyGame(ctx context.Context, gameID string) (*model.VerifyResult, error) {
	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	game, result, err := r.GameService.VerifyGame(ctx, id)
	if err != nil {
		return nil, err
	}

	cellResults := make([]*model.CellVerifyResult, len(result.Results))
	for i, r := range result.Results {
		feedback := model.CellFeedback(r.Feedback)
		cellResults[i] = &model.CellVerifyResult{
			Row:      r.Row,
			Col:      r.Col,
			Feedback: feedback,
		}
	}

	return &model.VerifyResult{
		Game:              domainGameToModel(game),
		Results:           cellResults,
		AllCorrect:        result.AllCorrect,
		MistakesThisRound: result.Mistakes,
	}, nil
}

// SubmitAnswer is the resolver for the submitAnswer field.
func (r *mutationResolver) SubmitAnswer(ctx context.Context, guestID string, puzzleID string, answers []*model.CellInput) (*model.SubmitAnswerResult, error) {
	guestUUID, err := resolveGuestUUID(ctx, guestID)
	if err != nil {
		return nil, err
	}

	// Parse puzzle ID
	puzzleUUID, err := uuid.Parse(puzzleID)
	if err != nil {
		return nil, err
	}

	// Convert answers to domain
	domainAnswers := make([]domain.CellInput, len(answers))
	for i, answer := range answers {
		domainAnswers[i] = domain.CellInput{
			Row:   answer.Row,
			Col:   answer.Col,
			Value: answer.Value,
		}
	}

	// Submit answers
	result, err := r.GameService.SubmitAnswer(ctx, guestUUID, puzzleUUID, domainAnswers)
	if err != nil {
		return nil, err
	}

	// Convert results
	cellResults := make([]*model.CellVerifyResult, len(result.Results))
	for i, r := range result.Results {
		feedback := model.CellFeedback(r.Feedback)
		cellResults[i] = &model.CellVerifyResult{
			Row:      r.Row,
			Col:      r.Col,
			Feedback: feedback,
		}
	}

	// Convert game result
	gameResult := &model.GameResult{
		ID:            result.Game.ID.String(),
		GuestID:       result.Game.GuestID.String(),
		PuzzleID:      result.Game.PuzzleID.String(),
		GridCurrent:   domainGridToModel(result.Game.GridCurrent),
		TotalMistakes: result.Game.TotalMistakes,
		Status:        model.GameStatus(result.Game.Status),
		CreatedAt:     result.Game.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:     result.Game.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}

	return &model.SubmitAnswerResult{
		Game:    gameResult,
		Results: cellResults,
	}, nil
}

// CompleteGame mutation resolver
func (r *mutationResolver) CompleteGame(ctx context.Context, gameID string, guestID string, username string) (*model.CompleteGameResult, error) {
	guestUUID, err := resolveGuestUUID(ctx, guestID)
	if err != nil {
		return nil, err
	}

	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	game, err := r.GameService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	entry, rank, err := r.LeaderboardService.Submit(ctx, id, guestUUID, username, game.TotalMistakes)
	if err != nil {
		return nil, err
	}

	return &model.CompleteGameResult{
		Entry: &model.LeaderboardEntry{
			ID:        entry.ID.String(),
			GuestID:   entry.GuestID.String(),
			Username:  entry.Username,
			Mistakes:  entry.Mistakes,
			CreatedAt: entry.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		},
		Rank: rank,
	}, nil
}

// UnlockPuzzlesAfterAd is the resolver for the unlockPuzzlesAfterAd field.
func (r *mutationResolver) UnlockPuzzlesAfterAd(ctx context.Context, guestID string) (*model.GuestSetProgress, error) {
	guestUUID, err := resolveGuestUUID(ctx, guestID)
	if err != nil {
		return nil, err
	}

	// Unlock next set for guest
	progress, err := r.PuzzleService.UnlockNextSet(ctx, guestUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to unlock next set: %w", err)
	}

	return domainGuestSetProgressToModel(progress), nil
}

// RefreshGameConfig is the resolver for the refreshGameConfig field (admin only).
func (r *mutationResolver) RefreshGameConfig(ctx context.Context) (*model.GameSettings, error) {
	// Verify admin token
	if err := checkAdminToken(ctx); err != nil {
		return nil, err
	}

	// Refresh config from database
	settings, err := r.AdminService.RefreshConfig()
	if err != nil {
		return nil, fmt.Errorf("failed to refresh config: %w", err)
	}

	return &model.GameSettings{
		StaminaMax:                  settings.StaminaMax,
		StaminaRegenIntervalMinutes: settings.StaminaRegenIntervalMinutes,
		StaminaRegenAmount:          settings.StaminaRegenAmount,
		InitialScore:                settings.InitialScore,
		ScoreDeductionPerMistake:    settings.ScoreDeductionPerMistake,
		ScoreMinimum:                settings.ScoreMinimum,
	}, nil
}

// AdminForceCompletePuzzles is the resolver for the adminForceCompletePuzzles field.
func (r *mutationResolver) AdminForceCompletePuzzles(ctx context.Context, guestID string) (*model.GuestSetProgress, error) {
	// Verify admin token
	if err := checkAdminToken(ctx); err != nil {
		return nil, err
	}

	// Parse guest UUID
	guestUUID, err := uuid.Parse(guestID)
	if err != nil {
		return nil, fmt.Errorf("invalid guest ID: %w", err)
	}

	// Force complete all puzzles in current unlocked set
	progress, err := r.AdminService.ForceCompletePuzzles(ctx, guestUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to force complete puzzles: %w", err)
	}

	// Convert to model
	return domainGuestSetProgressToModel(progress), nil
}

// Game query resolver
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	gameID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	game, err := r.GameService.GetByID(ctx, gameID)
	if err != nil {
		return nil, err
	}

	return domainGameToModel(game), nil
}

// GetGameByGuestAndPuzzle is the resolver for the getGameByGuestAndPuzzle field.
func (r *queryResolver) GetGameByGuestAndPuzzle(ctx context.Context, guestID string, puzzleID string) (*model.GameResult, error) {
	panic(fmt.Errorf("not implemented: GetGameByGuestAndPuzzle - getGameByGuestAndPuzzle"))
}

// GetAvailablePuzzles is the resolver for the getAvailablePuzzles field.
func (r *queryResolver) GetAvailablePuzzles(ctx context.Context, guestID string, limit *int) ([]*model.PuzzleWithStatus, error) {
	guestUUID, err := resolveGuestUUID(ctx, guestID)
	if err != nil {
		return nil, err
	}

	// Set default limit
	l := 20
	if limit != nil {
		l = *limit
	}

	// Get available puzzles for this guest with their status
	// Note: PuzzleService.GetAvailableForGuest already populates SolvedPositions
	// for COMPLETED and PLAYING puzzles, so we don't need to fetch game state separately
	puzzles, err := r.PuzzleService.GetAvailableForGuest(ctx, guestUUID, l)
	if err != nil {
		return nil, err
	}

	// Convert to model - solved positions are already included in the puzzle data
	result := make([]*model.PuzzleWithStatus, len(puzzles))
	for i, puzzle := range puzzles {
		if puzzle == nil || puzzle.Puzzle == nil {
			continue
		}
		result[i] = domainPuzzleWithStatusToModel(puzzle)
	}

	return result, nil
}

// GetCurrentSet is the resolver for the getCurrentSet field.
func (r *queryResolver) GetCurrentSet(ctx context.Context, guestID string) (*model.GuestSetProgress, error) {
	guestUUID, err := resolveGuestUUID(ctx, guestID)
	if err != nil {
		return nil, err
	}

	// Get current unlocked set for guest
	progress, err := r.PuzzleService.GetCurrentSet(ctx, guestUUID)
	if err != nil {
		return nil, err
	}

	return domainGuestSetProgressToModel(progress), nil
}

// Puzzles query resolver - Get all puzzles from puzzle pool
func (r *queryResolver) Puzzles(ctx context.Context) ([]*model.Puzzle, error) {
	puzzles, err := r.PuzzleService.GetAll(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Puzzle, len(puzzles))
	for i, puzzle := range puzzles {
		result[i] = domainPuzzleToModel(puzzle)
	}

	return result, nil
}

// Leaderboard query resolver
func (r *queryResolver) Leaderboard(ctx context.Context, limit *int) ([]*model.LeaderboardEntry, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	entries, err := r.LeaderboardService.GetTop(ctx, l)
	if err != nil {
		return nil, err
	}

	result := make([]*model.LeaderboardEntry, len(entries))
	for i, entry := range entries {
		result[i] = &model.LeaderboardEntry{
			ID:        entry.ID.String(),
			GuestID:   entry.GuestID.String(),
			Username:  entry.Username,
			Mistakes:  entry.Mistakes,
			CreatedAt: entry.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		}
	}

	return result, nil
}

// PuzzleStats query resolver
func (r *queryResolver) PuzzleStats(ctx context.Context, puzzleID string) (*model.PuzzleStats, error) {
	id, err := uuid.Parse(puzzleID)
	if err != nil {
		return nil, err
	}

	stats, err := r.GameService.GetPuzzleStats(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.PuzzleStats{
		PuzzleID:        stats.PuzzleID.String(),
		TotalPlayers:    stats.TotalPlayers,
		TotalCompleted:  stats.TotalCompleted,
		AverageMistakes: stats.AverageMistakes,
	}, nil
}

// PlayerStats query resolver
func (r *queryResolver) PlayerStats(ctx context.Context, guestID string) (*model.PlayerStats, error) {
	id, err := uuid.Parse(guestID)
	if err != nil {
		return nil, err
	}

	stats, err := r.GameService.GetPlayerStats(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.PlayerStats{
		GuestID:          stats.GuestID.String(),
		PuzzlesCompleted: stats.PuzzlesCompleted,
		TotalPuzzles:     stats.TotalPuzzles,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
