package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/kenshero/100sumgame/internal/domain"
	"github.com/kenshero/100sumgame/internal/graphql/generated"
	"github.com/kenshero/100sumgame/internal/graphql/model"
	"github.com/kenshero/100sumgame/internal/middleware"
)

// CreateGame mutation resolver
func (r *mutationResolver) CreateGame(ctx context.Context, guestID string) (*model.Game, error) {
	// Get session from context
	session := middleware.GetSessionFromContext(ctx)
	if session == nil {
		return nil, fmt.Errorf("session not found")
	}

	// Parse guest ID from session
	guestUUID, err := uuid.Parse(session.GuestID)
	if err != nil {
		return nil, err
	}

	game, err := r.GameService.CreateGame(ctx, guestUUID)
	if err != nil {
		return nil, err
	}

	return domainGameToModel(game), nil
}

// FillCells mutation resolver
func (r *mutationResolver) FillCells(ctx context.Context, gameID string, cells []*model.CellInput) (*model.Game, error) {
	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	domainCells := make([]domain.CellInput, len(cells))
	for i, cell := range cells {
		domainCells[i] = domain.CellInput{
			Row:   cell.Row,
			Col:   cell.Col,
			Value: cell.Value,
		}
	}

	game, err := r.GameService.FillCells(ctx, id, domainCells)
	if err != nil {
		return nil, err
	}

	return domainGameToModel(game), nil
}

// MakeMove mutation resolver
func (r *mutationResolver) MakeMove(ctx context.Context, gameID string, row int, col int, value int) (*model.MoveResult, error) {
	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	result, err := r.GameService.MakeMove(ctx, id, row, col, value)
	if err != nil {
		return nil, err
	}

	feedback := model.CellFeedback(result.Feedback)

	return &model.MoveResult{
		Game:          domainGameToModel(result.Game),
		IsCorrect:     result.IsCorrect,
		Feedback:      feedback,
		TotalMistakes: result.TotalMistakes,
		IsGameOver:    result.IsGameOver,
	}, nil
}

// VerifyGame mutation resolver
func (r *mutationResolver) VerifyGame(ctx context.Context, gameID string) (*model.VerifyResult, error) {
	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	game, result, err := r.GameService.VerifyGame(ctx, id)
	if err != nil {
		return nil, err
	}

	cellResults := make([]*model.CellVerifyResult, len(result.Results))
	for i, r := range result.Results {
		feedback := model.CellFeedback(r.Feedback)
		cellResults[i] = &model.CellVerifyResult{
			Row:      r.Row,
			Col:      r.Col,
			Feedback: feedback,
		}
	}

	return &model.VerifyResult{
		Game:              domainGameToModel(game),
		Results:           cellResults,
		AllCorrect:        result.AllCorrect,
		MistakesThisRound: result.Mistakes,
	}, nil
}

// CompleteGame mutation resolver
func (r *mutationResolver) CompleteGame(ctx context.Context, gameID string, guestID string, username string) (*model.CompleteGameResult, error) {
	// Get session from context
	session := middleware.GetSessionFromContext(ctx)
	if session == nil {
		return nil, fmt.Errorf("session not found")
	}

	// Parse guest ID from session (ignore the guestID parameter from client)
	guestUUID, err := uuid.Parse(session.GuestID)
	if err != nil {
		return nil, err
	}

	id, err := uuid.Parse(gameID)
	if err != nil {
		return nil, err
	}

	game, err := r.GameService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	entry, rank, err := r.LeaderboardService.Submit(ctx, id, guestUUID, username, game.TotalMistakes)
	if err != nil {
		return nil, err
	}

	return &model.CompleteGameResult{
		Entry: &model.LeaderboardEntry{
			ID:        entry.ID.String(),
			GuestID:   entry.GuestID.String(),
			Username:  entry.Username,
			Mistakes:  entry.Mistakes,
			CreatedAt: entry.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		},
		Rank: rank,
	}, nil
}

// Game query resolver
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	gameID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	game, err := r.GameService.GetByID(ctx, gameID)
	if err != nil {
		return nil, err
	}

	return domainGameToModel(game), nil
}

// Puzzles query resolver - Get all puzzles from puzzle pool
func (r *queryResolver) Puzzles(ctx context.Context) ([]*model.Puzzle, error) {
	puzzles, err := r.PuzzleService.GetAll(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Puzzle, len(puzzles))
	for i, puzzle := range puzzles {
		result[i] = domainPuzzleToModel(puzzle)
	}

	return result, nil
}

// Leaderboard query resolver
func (r *queryResolver) Leaderboard(ctx context.Context, limit *int) ([]*model.LeaderboardEntry, error) {
	l := 10
	if limit != nil {
		l = *limit
	}

	entries, err := r.LeaderboardService.GetTop(ctx, l)
	if err != nil {
		return nil, err
	}

	result := make([]*model.LeaderboardEntry, len(entries))
	for i, entry := range entries {
		result[i] = &model.LeaderboardEntry{
			ID:        entry.ID.String(),
			GuestID:   entry.GuestID.String(),
			Username:  entry.Username,
			Mistakes:  entry.Mistakes,
			CreatedAt: entry.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		}
	}

	return result, nil
}

// PuzzleStats query resolver
func (r *queryResolver) PuzzleStats(ctx context.Context, puzzleID string) (*model.PuzzleStats, error) {
	id, err := uuid.Parse(puzzleID)
	if err != nil {
		return nil, err
	}

	stats, err := r.GameService.GetPuzzleStats(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.PuzzleStats{
		PuzzleID:        stats.PuzzleID.String(),
		TotalPlayers:    stats.TotalPlayers,
		TotalCompleted:  stats.TotalCompleted,
		AverageMistakes: stats.AverageMistakes,
	}, nil
}

// PlayerStats query resolver
func (r *queryResolver) PlayerStats(ctx context.Context, guestID string) (*model.PlayerStats, error) {
	id, err := uuid.Parse(guestID)
	if err != nil {
		return nil, err
	}

	stats, err := r.GameService.GetPlayerStats(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.PlayerStats{
		GuestID:          stats.GuestID.String(),
		PuzzlesCompleted: stats.PuzzlesCompleted,
		TotalPuzzles:     stats.TotalPuzzles,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
